### ISSUE TITLE
Support Azure Active Directory

### ISSUE THREAD

**Issue by savas-guven** [deepnetworkgmbh/joseki#215]
- [ ] Automation of Infrastructure for Azure AD via scripts #248
- [ ] Authentication frontend implementation #249
- [ ] Authentication API implementation #250
- [ ] Authorization Role Assignments #251 
- [ ] Authorization API implementation #252

**Comment by v1r7u** [comment]
Review after #222
