### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by detaybey** [deepnetworkgmbh/joseki#38]
- [x] Landing Page (Overview of entire scans)
- [x] Overview history page #39 
- [x] Overview diff page #42 
- [x] Subscription details page #43
- [x] Cluster details page #44
- [x] Image details page
- [x] Subscription history page #45 
- [x] Cluster history page #46 
- [x] Subscription diff page #47 
- [x] Cluster diff page #48
